name: homescapes
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_functions: ^4.7.6
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_analytics: ^10.10.7
  firebase_messaging: ^14.7.10
  google_sign_in: 6.2.1
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  flutter_widget_from_html_core: ^0.16.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  flutter_web_auth_2: ^5.0.1
  google_mobile_ads: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - childTimeTable.pdf
    - assets/maps/child_timetable_page1.png
    - assets/maps/child_timetable_page2.png
    - assets/maps/map_1.png
    - assets/maps/map_2.png
    - assets/img/icon/
    - assets/img/google_login/
    - assets/img/apple_login/
    - assets/img/naver_login/
    - assets/img/kakao_login/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21
